baseURL = "http://examplesite.org"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "ALIS Kontor Sør - Kristiansand"
[Languages.en]
contentDir = "content/english"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "Om oss"
weight = 1
[[Languages.en.menu.footer]]
URL = "project"
name = "Prosjekter"
weight = 2
[[Languages.en.menu.footer]]
URL = "service"
name = "Tjenester"
weight = 3
[[Languages.en.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.en.menu.footer]]
URL = "contact"
name = "Kontakt oss"
weight = 6
[[Languages.en.menu.main]]
URL = "/"
name = "Hjem"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "Om oss"
weight = 2
[[Languages.en.menu.main]]
URL = "project"
name = "Prosjekter"
weight = 3
[[Languages.en.menu.main]]
URL = "service"
name = "Tjenester"
weight = 4
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.en.menu.main]]
hasChildren = true
name = "Mer info"
weight = 6
[[Languages.en.menu.main]]
URL = "faq"
name = "Fastlegeordningen"
parent = "Mer info"
[[Languages.en.menu.main]]
URL = "pricing"
name = "Rapporter"
parent = "Mer info"
[[Languages.en.menu.main]]
URL = "contact"
name = "Kontakt oss"
weight = 7
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "demo@email.com"
google_analitycs_id = ""
location = "Tollbodgata 22, 4611 Kristiansand"
logo = "images/logo.png"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "58.145801"
map_longitude = "7.996957"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
